# 通过环境变量`HOSTS`传递了两条hosts条目，并将其重定向输入到容器的 /etc/hosts 文件。这样，容器内部就会有额外的hosts解析。
# 请注意，这种方法需要容器内有适当的权限去写入`/etc/hosts`文件，并且这种修改是临时的，不会影响Pod重启后的状态。
# 如果需要持久化修改，可以考虑使用ConfigMap或者DaemonSet等其他方案。


apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-image
    env:
    - name: HOSTS
      value: |
        123.123.123.123 my.custom.domain
        192.168.1.1 my.local.domain
    command: ["/bin/sh"]
    args:
    - "-c"
    - >
      set -e
      echo $HOSTS > /etc/hosts
      
      
# 其他启动命令