apiVersion: v1
kind: Pod
metadata:
  labels:
    test: read
  name: read
spec:
  containers:
    - name: my-container
      image: nginx
      imagePullPolicy: IfNotPresent
      readinessProbe:       #  启动探针
        httpGet:          
          path: /readiness       # http具体访问路径
          port: 80               # 具体访问端口
        initialDelaySeconds: 20
        periodSeconds: 5
        failureThreshold: 3
      volumeMounts:
      - name: nginx-html
        mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-html
      hostPath:
        path: /data/nginx

        # initialDelaySeconds: 5 # 指定5秒后才开始探测
        # periodSeconds: 5       # 每隔几秒来运行这个
        # timeoutSeconds: 5      # 探测超时，到了超时时间探测还没返回结果说明失败
        # successThreshold: 3    # 成功阈值，连续几次成功才算成功
        # failureThreshold: 5    # 失败阈值，连续几次失败才算失败