apiVersion: v1
kind: Pod
metadata:
  name: "ubuntu"
  namespace: default
  labels:
    app: "ubuntu"
spec:
  containers:
  - name: ubuntu
    image: "registry.cn-hangzhou.aliyuncs.com/lw_docker_images/ubuntu:lstest"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    volumeMounts:
    - name: localtime
      mountPath: /etc/localtime
  volumes:
    - name: localtime
      hostPath:
        path: /usr/share/zoneinfo/Asia/Shanghai
  restartPolicy: Always