# k8s集群的每个机器(每一个节点)都运行一个程序(默认master除外，master节点默认不会把Pod调度过去)

# Daemonset 控制器确保所有(或一部分)的节点都运行了一个指定的 Pod 副本。

# 无法指定副本数量
#   - 每当向集群中添加一个节点时，指定的 Pod 副本也将添加到该节点上
#   - 当节点从集群中移除时，Pod 也就被垃圾回收了
#   - 删除一个 Daemonset 可以清理所有由其创建的 Pod

# Daemonset的典型使用场景有:
# - 在每个节点上运行集群的存储守护进程，例如glusterd、ceph
# - 在每个节点上运行日志收集守护进程，例如 fluentd、logstash
# - 在每个节点上运行监控守护进程，
#   - 例如： Prometheus Node_Exporter、SysdigAgent、collectd、Dynatrace
#     OneAgent、APPDynamicsAgent、 Datadog agent、 New Relic agent、Ganglia gmond、 Instana Agent 等


---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-test
  namespace: default
  labels:
    app: ds-test
spec:
  selector:
    matchLabels:
      app: ds-test
  template:
    metadata:
      labels:
        app: ds-testp
    spec:
      tolerations:           # 设置pod可以容忍污点
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: ds-test
        image: nginx
        imagePullPolicy: IfNotPresent