# 容器的存活探针,循环检测容器是否存活，如果失败就自动重启容器

apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: busybox
    args:  # 创建一个文件睡30秒，30后删除，再睡600秒
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:             # 容器存活探针
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5   # 容器启动Running5秒以后开始探测
      periodSeconds: 5         # 每隔5秒进行一次探测