apiVersion: v1
kind: Pod
metadata:
  name: "nginx-start-probe-test-o2"
  namespace: default
  labels:
    app: "nginx-start-probe-test-o2"
spec:
  volumes:
  - name: nginx-vol
    hostPath: 
      path: /app
  - name: nginx-html
    hostPath:
      path: /html
  containers:
  - name: nginx
    image: "nginx"
    ports:
    - contaenerPort: 80
    startupProbe:        # 启动探针，
      exec: 
        command: ["/bin/sh","-c","cat /usr/share/nginx/html/abc.html "]
      periodSeconds: 5
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3
    livenessProbe:     # 存活探针
      # httpGet:
      #   host: 127.0.0.1
      #   path: /abc.html
      #   port: 80
      #   scheme: HTTP
      exec:        # 返回值不是0，就是探测失败
        command: ["/bin/sh","-c","cat /usr/share/nginx/html/abc.html"]
      periodSeconds: 5
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 5
    readinessProbe:   # 就绪检测探针
      httpGet:
      #  host: 127.0.0.1 指定本地127地址一直为拒绝连接
        path: /abc.html
        port: 80
        scheme: HTTP
      periodSeconds: 5
      timeoutSeconds: 5
      successThreshold: 3
      failureThreshold: 5
    volumeMounts:
    - name: nginx-vol
      mountPath: /app
    - name: nginx-html
      mountPath: /usr/share/nginx/html

      # initialDelaySeconds: 5 # 指定5秒后才开始探测
      # periodSeconds: 5       # 每隔几秒来运行这个
      # timeoutSeconds: 5      # 探测超时，到了超时时间探测还没返回结果说明失败
      # successThreshold: 3    # 成功阈值，连续几次成功才算成功
      # failureThreshold: 5    # 失败阈值，连续几次失败才算失败